### PR TITLE
Remove exponent params of some curves

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by ValarDragon** [comment]
Thanks for submitting a PR to remove the deadcode!

This would be a breaking change, though I'm not sure how likely it is that another project would be using these final exponents.

**Comment by Pratyush** [comment]
AFAIK, there's no use for the final exponent besides the pairing (where there are faster algorithms, as you noted)

**Comment by chfast** [comment]
I don't remember what was the exact reason for this, probably some static analysis tool reported these as unused.
I don't care really. It you think this is breaking change it is probably not worth it.

**Review by ValarDragon — DISMISSED** [review]
LGTM, just need to wait for the next breaking change to the library to merge this in.

**Review by ValarDragon — DISMISSED** [review]

**Review by ValarDragon — APPROVED** [review]

**Pull request merged**
